Update pretty_var function; merge print_poly into show
  1. Merged the `print_poly` function directly into `Base.show`, as `print_poly` was only being used in the `show` definition (i.e., the function was redundant).

  2. The `pretty_var` function was not printing correctly, causing tests to fail—the reason for this is because polynomials would sometimes print in the form
```julia
2z₂⁴
```
But sometimes of the form
```julia
2z[2]⁴
```
I'm not sure what caused that, nor for how long the tests were broken, but I just added an extra regex matching in the `pretty_var` function to capture this.  The only thing failing now is converting variables of `Polynomial` to `Symbol`s correctly:
```julia
poly: Test Failed at /home/jakewilliami/projects/FixedPolynomials.jl/test/poly_test.jl:41
  Expression: variables(F[1]) == [:z1, :z2]
   Evaluated: [Symbol("z[1]"), Symbol("z[2]")] == [:z1, :z2] 
# ...
Test Summary: | Pass  Fail  Total
poly          |   50     1     51
ERROR: LoadError: LoadError: Some tests did not pass: 50 passed, 1 failed, 0 errored, 0 broken.
```